---
title: "Are Mandatory Publications of Financial Statements Economically Efficient?"
subtitle: "ECO 320 Assignment"
format: pdf
author: Diana Liu
date: "2024 March 13"
bibliography: references.bib
header-includes:
  - \usepackage{indentfirst}
  - \usepackage{setspace}
indent: true
fontsize: 12pt
linestretch: 2
---
## Required Disclosure of Asymmetric Information in the Status Quo
Public companies are companies that have their stocks traded on an exchange like the New York Stock Exchange.The biggest benefit to being publicly traded is to raise funds from investors purchasing your stock. However, in order to be publicly traded, companies are required by law in Canada and the U.S. to regularly make information about their activities and financial status available to the public [@CiteOSC]. This process is known as continuous disclosure and is achieved through publishing quarterly and annual reports, like financial statements, executive compensation, and forward looking information circulars [@CiteOSC]. This requirement falls under the normative Hobbes Theorem where the law is structured to minimize harms caused by failures in private bargaining [@CiteCooter, 92].

Continuous disclosure provides valuable information that investors  use to make decisions about the company in question. This information requires deliberate investment by the company to collect and organize, but companies often already have internal systems to acquire information for business decision making. This results in asymmetric information between companies and their stakeholders where companies have information readily available and stakeholders need to invest in deliberately searching for the same information. Required disclosure of this information in the status quo turns it from the property of the company into a public good, solving this asymmetry, but incurs both costs and benefits of its own.

## Cost and Time Savings from Searching for Information
If it is assumed that it costs the same amount for an investor to gather continuous disclosure information as the company itself already invested, then requiring disclosure saves for investors the socially wasteful costs of searching for information that the company already has [@CiteEisenberg, 1611]. To illustrate this, imagine that company A is selling shares, an investor is considering whether or not to buy them, and disclosure not required by law. The investor want to know the financial information of company A so that they can be confident that their investment will increase in value. If company A already has information the investor wants and believe that the information proves that they are in good financial health thus increasing the chances of securing a loan, they will share the information willingly. This saves the investor costs of acquiring the information. On the other hand, if company A is not financially successful and believe that the information will decrease their chances of an investment, they will not willingly share the information, forcing the investor to spend money gathering information that company A already has, creating social inefficiency. In this case, compelling the company to publish this information by law saves the investor the cost of searching for information. 

Outside of information gathering costs, the immediate availability of continuous disclosure information also allows faster allocation of goods to their highest-valued uses. Suppose that company B is competing for an investment with company A and company B has higher value use for the loan than company A. If the investor takes time to search for company A's financial information, the funds will remain un-allocated until the investor gathers enough information to decide which company to loan to. This is less efficient than if both companies' information were readily available because the investor can find the most efficient allocation of the loan immediately, saving the time it takes to transfer the funds to its highest value user.

## Correcting Mistaken Assumptions
Investors tend to hold on to shares for a period of time, during which mistaken assumptions can lead them to continue investing even though the investment has turned unprofitable. According to Kronman, "allocative efficiency is promoted by getting information of changed circumstances to the market as quickly as possible so that parties affected by the information can alter their behaviour to waste as little resources as possible" [@CiteKronman, 13]. When companies are required to continuously disclose information, usually quarterly at minimum, it allows their investors to quickly react to changed circumstances.

Suppose that companies are only required to disclose their financial and operational information once and not continuously. In a market for investments, suppliers are investors who lend out funds and demand is companies who want investments. At first, all companies disclose their financial and operational information and investors choose investments accordingly, the market starts out in equilibrium. Then circumstances change causing the companies to be no longer as profitable, shifting the demand curve upward as they need more investment to remain open. However this is not disclosed to the suppliers who continue to invest at the previous equilibrium amount, there is now dead weight loss and the market is no longer allocatively efficient. If continuous disclosure is required, then suppliers will realize that the demand has increased and adjust the ammount supplied accordingly, maintaining allocative efficiency.

## Over Reliance
Over reliance on continuous disclosure information can harm investors, as the requirement of disclosure can lead to inefficiency by decreasing the incentive to invest in the discovery of productive information [@CiteEisenberg, 1676]. For instance, financial information can be legally manipulated to make the company seem more prosperous than it actually is. Even if financial statements are audited, verified by an independent 3rd party, the manipulation can still occur to the detriment of investors [@CiteEnron]. Stakeholders may over-rely on the validity of these statements and do nothing to verify or discover information to the contrary. This results in mistaken assumptions going uncorrected which increases the time and resources needed to move goods to their highest value users.

## Blanket Rule

## Conclusion

\newpage
## Appendix
### Stakeholders
A stakeholder in a company is an individual or organization whose well being will be effected by the financial and operational health of the company. This means that they directly benefit from required disclosure where financial and operational information that they want to know are shared at no cost to them. For example, creditors who are owed money by the company want to know if the company has enough income to repay them. Other stakeholders include shareholders, suppliers, customers, employees, and unions among others.

\newpage
## References
